FORMAT: 1A
HOST: http://oa.ecjtu.net/

# OAmanagement

学团OA系统

  * api的使用基于oauth2，请先[前往](http://oa.ecjtu.net/oauth/oauth_client/create)注册应用。
  * 所有api的使用请携带access_token作为请求参数(除api/v1/oauth/access_token)
  * 大部分api的使用请携带token作为请求参数（通过api/v1/user/login获得）
  
## OAUTH2 [/api/v1/oauth/access_token]

### 获取access_token [POST]

+ Request (application/x-www-form-urlencoded)

                {
                    "grant_type": "authorization_code",
                    "client_id": "jcZNHoAzmYD7wyyG571jXoT5IjhzaU4tTR3iVZ",
                    "client_secret": "VKIDoT5j88dZf2OD53aDNzDX8OroCigBhW5K0F",
                    "redirect_uri": "http://laravel.dev:8000/oauth/oauth_client/code",
                    "code": "vY6FNU8jH8DOHF4Vint3iXN4z8UkDjdfGYyHGU5l"  
                }

+ Response 200 (application/json)

    + Headers
    
                ETag: 4d31f1fe87715aa106c1e22f128b0dee
    
    + Body
    
                {
                  "access_token": "wWbjWXmxiUeFBspTDhcr7TbjQ7RbLmCcao0qoX5Z",
                  "token_type": "Bearer",
                  "expires_in": 7776000
                }


## 用户 [/api/v1/users]

### 获取所有用户 [GET]