FORMAT: 1A
HOST: http://oa.ecjtu.net/

# OAmanagement

学团OA系统

  * api的使用基于oauth2，请先[前往](http://oa.ecjtu.net/oauth/oauth_client/create)注册应用。
  * 所有api的使用请携带access_token作为请求参数(除api/v1/oauth/access_token)
  * 大部分api的使用请携带token(JWT)作为请求参数（通过api/v1/user/login获得）
  
## OAUTH2 [/api/v1/oauth/access_token]

### 获取access_token [POST]

+ Request (application/x-www-form-urlencoded)

                {
                    "grant_type": "authorization_code",
                    "client_id": "jcZNHoAzmYD7wyyG571jXoT5IjhzaU4tTR3iVZ",
                    "client_secret": "VKIDoT5j88dZf2OD53aDNzDX8OroCigBhW5K0F",
                    "redirect_uri": "http://laravel.dev:8000/oauth/oauth_client/code",
                    "code": "vY6FNU8jH8DOHF4Vint3iXN4z8UkDjdfGYyHGU5l"  
                }

+ Response 200 (application/json)

    + Headers
    
                ETag: 4d31f1fe87715aa106c1e22f128b0dee
    
    + Body
    
                {
                  "access_token": "wWbjWXmxiUeFBspTDhcr7TbjQ7RbLmCcao0qoX5Z",
                  "token_type": "Bearer",
                  "expires_in": 7776000
                }


## 用户注册 [/api/v1/user/register]

### 用户注册 [POST]

+ Request (application/x-www-form-urlencoded)

                {
                    "access_token": "wWbjWXmxiUeFBspTDhcr7TbjQ7RbLmCcao0qoX5Z",
                    "User_phone": "12345678911",
                    "User_password": "iampassword"
                }
                
+ Response 200 (application/json)

                {
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjI0LCJpc3MiOiJodHRwOlwvXC9sYXJhdmVsLmRldjo4MDAwXC9hcGlcL3YxXC91c2VyXC9yZWdpc3RlciIsImlhdCI6MTQ3MjAwMTE1NiwiZXhwIjoxNDcyMDA0NzU2LCJuYmYiOjE0NzIwMDExNTYsImp0aSI6ImVkOTAzMTJlODc5M2ZlYTNjZGZkNTVlZWE2MzZiMDU4In0.-HgcTtA8gJSOPxypfhvbqDD7Z95YpRfZxQP6WtHxCKM"
                }
                
                
## 用户登录 [/api/v1/user/login]

### 用户登录 [POST]

+ Request (application/x-www-form-urlencoded)

                {
                    "access_token": "wWbjWXmxiUeFBspTDhcr7TbjQ7RbLmCcao0qoX5Z",
                    "phone": "12345678911",
                    "password": "iampassword"
                }
                
+ Response 200 (application/json)

                {
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjI0LCJpc3MiOiJodHRwOlwvXC9sYXJhdmVsLmRldjo4MDAwXC9hcGlcL3YxXC91c2VyXC9sb2dpbiIsImlhdCI6MTQ3MjAwMjY0OCwiZXhwIjoxNDcyMDA2MjQ4LCJuYmYiOjE0NzIwMDI2NDgsImp0aSI6ImFmODNjMWU3NjAwZTI1ZGRiMTkxZmFiNzkwYTdkMGNjIn0.IINYpew92Wd7YWlUnom0Bo0xIaYwwrYB0mWj21sq8Ec"
                }
                
                
## 获取当前用户 [/api/v1/user/me?access_token=null;token=null]

+ Parameters

    + access_token (string) - Oauth识别码
    + token (string) - JWT识别码

### 当前用户 [GET]

+ Response 200 (application/json)

                {
                    "data": {
                        "User_id": 24,
                        "User_name": "user_CG8Wxe",
                        "User_phone": "12345678911",
                        "User_student_id": null,
                        "User_confirmed": false
                    }
                }